FROM node:16 as builder
WORKDIR /app
COPY ./frontend/package*.json /app/
RUN npm install
COPY ./frontend /app/
RUN npm run build


FROM nginx:1.17-alpine
RUN apk --no-cache add curl
COPY ./frontend/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build/ /usr/share/nginx/html
EXPOSE 80
