#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 5091


FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["EnergyConsumptionBackendApp/EnergyConsumptionBackendApp/EnergyConsumptionBackendApp.csproj", "EnergyConsumptionBackendApp/"]
RUN dotnet restore "EnergyConsumptionBackendApp/EnergyConsumptionBackendApp.csproj"
COPY . .
WORKDIR "/src/EnergyConsumptionBackendApp"
RUN dotnet build "EnergyConsumptionBackendApp/EnergyConsumptionBackendApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EnergyConsumptionBackendApp.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EnergyConsumptionBackendApp.dll"]